import 'package:flutter/material.dart';

void main()=> runApp(Myapp());
class Myapp extends StatelessWidget {
  const Myapp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(brightness: Brightness.dark,primaryColor: Colors.deepPurple),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Column(
          children: [
            Row(children: [
              Container(
                width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("H",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic),)),
              ),
              SizedBox(width: 657,),
              Container(
                width: 40,
                height: 40,
                color:Colors.blue,
                child: Center(child: Text("He",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic),)),
              )
            ],),
            SizedBox(height: 1,),
            Row(
              children: [
                Container(
                  width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Li",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                 width: 40,
                height: 40,
                color:Colors.yellow,
                child: Center(child: Text("Be",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 411,),
                Container(
                 width: 40,
                height: 40,
                color:Colors.lightBlue,
                child: Center(child: Text("B",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                 width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("C",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                 width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("N",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                 width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("O",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                 width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("F",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                 width: 40,
                height: 40,
                color:Colors.blue,
                child: Center(child: Text("Ne",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
              ],
            ),
            SizedBox(height: 1,),
            Row(
              children: [
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Na",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.yellow,
                child: Center(child: Text("Mg",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 411,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightBlue,
                child: Center(child: Text("Al",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightGreen,
                child: Center(child: Text("Si",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("P",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("S",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("Cl",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.blue,
                child: Center(child: Text("Ar",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
              ],
            ),
            SizedBox(height: 1,),
            Row(
              children: [
                Container(
                  width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("K",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.yellow,
                child: Center(child: Text("Ca",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Sc",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Ti",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("V",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Cr",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Mn",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Fe",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Co",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Ni",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Cu",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Zn",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightBlue,
                child: Center(child: Text("Ga",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightGreen,
                child: Center(child: Text("Ge",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightGreen,
                child: Center(child: Text("As",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("Se",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("Br",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.blue,
                child: Center(child: Text("Kr",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
              ],
            ),
            SizedBox(height: 1,),
            Row(
              children: [
                Container(
                  width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Rb",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.yellow,
                child: Center(child: Text("Sr",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Y",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Zr",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Nb",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Mo",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Tc",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Ru",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Rh",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Pd",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Ag",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Cd",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightBlue,
                child: Center(child: Text("In",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightBlue,
                child: Center(child: Text("Sn",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightGreen,
                child: Center(child: Text("Sb",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightGreen,
                child: Center(child: Text("Te",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("I",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.green,
                child: Center(child: Text("Xe",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),  
                ),
              ],
            ),
            SizedBox(height: 1,),
            Row(
              children: [
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Cs",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.yellow,
                child: Center(child: Text("Ba",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                //child: Center(child: Text("Cs",style: TextStyle(color: Colors.black,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Hf",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Ta",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("W",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Re",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Os",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Ir",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Pt",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Au",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Hg",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightBlue,
                child: Center(child: Text("Ti",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightBlue,
                child: Center(child: Text("Pb",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightBlue,
                child: Center(child: Text("Bi",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightBlue,
                child: Center(child: Text("Po",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightGreen,
                child: Center(child: Text("At",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.blue,
                child: Center(child: Text("Rn",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
              ],
            ),
            SizedBox(height: 1,),
            Row(
              children: [
                Container(
                   width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Fr",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.yellow,
                child: Center(child: Text("Ra",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Rf",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Db",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Sg",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Bh",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Hs",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.red,
                child: Center(child: Text("Mt",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.red,
                child: Center(child: Text("Ds",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.red,
                child: Center(child: Text("Rg",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.orange,
                child: Center(child: Text("Cn",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.red,
                child: Center(child: Text("Nh",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.lightBlue,
                child: Center(child: Text("Fl",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.red,
                child: Center(child: Text("Mc",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.red,
                child: Center(child: Text("Lv",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.red,
                child: Center(child: Text("Ts",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.red,
                child: Center(child: Text("Og",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
              ],
            ),
            SizedBox(height: 1,),
            Row(
              children: [
                Container(
                width: 40,
                height: 40,
                color:Colors.red,
                child: Center(child: Text("Uue",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
              ],
            ),
            SizedBox(height: 1,),
            Row(
              children: [
                Container(
                width: 40,
                height: 40, 
                ),
                SizedBox(width: 1,),
                Container(
                  width: 40,
                height: 40,
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("La",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Ce",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Pr",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Nd",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Pm",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Sm",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Eu",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Gd",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Tb",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Dy",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Ho",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Er",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Tm",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Yb",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.pink,
                child: Center(child: Text("Lu",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
              ],
            ),
            SizedBox(height: 1,),
            Row(
              children: [
                Container(
                width: 40,
                height: 40, 
                ),
                SizedBox(width: 1,),
                Container(
                  width: 40,
                height: 40,
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Ac",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Th",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Pa",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("U",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Np",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Pu",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Am",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Cm",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Bk",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Cf",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Es",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Fm",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Md",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("No",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
                SizedBox(width: 1,),
                Container(
                width: 40,
                height: 40,
                color:Colors.purple,
                child: Center(child: Text("Lr",style: TextStyle(color: Colors.white,fontStyle: FontStyle.italic))),
                ),
              ],
            )
          ],
        ),
      ),
    );
  }
}